package com.ascention.validationWS.rules

import com.ascention.validationWS.beans.*;


declare IsAdult
	person: Person
end
declare IsChild
	person: Person
end


rule IsChildPolicy when
    p : Person( age < 16 )
then
    insertLogical( new IsChild( p ) );
end

rule IsAdultPolicy when
    p : Person( age >= 16 )
then
    insertLogical( new IsAdult( p ) );
end


rule IssueChildBusPass when
    p : Person()
    IsChild( person == p )
then
    insertLogical( new ChildBusPass( p ) );
end

rule IssueAdultBusPass when
    p : Person()
    IsAdult( person == p )
then
    insertLogical( new AdultBusPass( p ) );
end


rule "135-009-001"
	when 
		productAdditionalObject: ProductAdditional(dg_class!=null && dg_class=="10")  
		result:Result()
	then
		result.setOutput("FAIL" + " 135-009-001");
	end
rule "350-G153-001"
	when 
		productAdditionalObject: ProductAdditional(dg_subsidiary_class!=null && dg_subsidiary_class==dg_class) 
		result:Result()
	then
		result.setOutput("FAIL" + " 350-G153-001");
	end
rule "135-009-003"
	when 
		productAdditionalObject: ProductAdditional(dg_class==null && dangerous_good=="true")  
		result:Result()
	then
		result.setOutput("FAIL" + " 135-009-003");
	end

rule "135-009-002"
	when 
		productAdditionalObject: ProductAdditional(dg_class!=null && dangerous_good=="true" && dg_class not in(1.4,2.1,2.2,2.3,3.0,4.1,4.2,4.3,5.1,5.2,6.1,7.0,8.0,9.0))  
		result:Result()
	then
		result.setOutput("FAIL" + " 135-009-002");
	end


rule "030-007-002"
	when
		productHierarchyObject: ProductHierarchy(depth_uom!=height_uom || width_uom!=height_uom )
		result: Result()
	then
		result.setOutput("FAIL" + " 030-007-002");
	end
	
rule "030-006-001"
	when
		(productHierarchyObject:ProductHierarchy(depth==null) && productCore: ProductCore(is_non_physical!="true")) || 
		(ProductHierarchy(depth!=null) && ProductHierarchy(depth <= 0)) 
		result: Result()
	then
		result.setOutput("FAIL" + " 030-006-001");
	end	
	
rule "TEST-MULTIOBJ-LIST"
	when		
		$productAdditionalArray : ProductAdditionalArray($lstProductAdditional : lstProductAdditional, eligibility )
  		ProductAdditional( eligibility ) from $lstProductAdditional		
		result: Result()
	then
		modify( $productAdditionalArray ){ setEligibility(false) }
		result.setOutput("{FAILED_TEST-MULTIOBJ-LIST:" + $productAdditionalArray.toString() + "}",1);      
	end	