//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.18 at 01:24:23 AM AEDT 
//


package com.ascention.GS1.pricing.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PriceSynchronisationRelationshipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceSynchronisationRelationshipType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="priceSynchronisationRelationshipIdentification" type="{urn:gs1:shared:shared_common:xsd:3}EntityIdentificationType"/&gt;
 *         &lt;element name="relationshipActionCode" type="{urn:gs1:gdsn:price_synchronisation_document:xsd:3}SegmentActionCodeType"/&gt;
 *         &lt;element name="relationshipCurrencyCode" type="{urn:gs1:shared:shared_common:xsd:3}CurrencyCodeType"/&gt;
 *         &lt;element name="relationshipEffectiveStartDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="relationshipLastChangedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="relationshipTradeChannel" type="{urn:gs1:gdsn:gdsn_common:xsd:3}TradeChannelCodeType"/&gt;
 *         &lt;element name="targetMarketCountryCode" type="{urn:gs1:shared:shared_common:xsd:3}CountryCodeType"/&gt;
 *         &lt;element name="priceSynchronisationRelationshipName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="relationshipEffectiveEndDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="specialScenarioCode" type="{urn:gs1:gdsn:price_synchronisation_document:xsd:3}PriceSynchronisationSpecialScenarioCodeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="incotermInformation" type="{urn:gs1:gdsn:gdsn_common:xsd:3}IncotermInformationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="businessLocation" type="{urn:gs1:shared:shared_common:xsd:3}PartyIdentificationType"/&gt;
 *         &lt;element name="informationProvider" type="{urn:gs1:shared:shared_common:xsd:3}PartyIdentificationType"/&gt;
 *         &lt;element name="partyReceivingPrivateData" type="{urn:gs1:shared:shared_common:xsd:3}PartyIdentificationType"/&gt;
 *         &lt;element name="extension" type="{urn:gs1:shared:shared_common:xsd:3}ExtensionType" minOccurs="0"/&gt;
 *         &lt;element name="avpList" type="{urn:gs1:gdsn:gdsn_common:xsd:3}GS1_AttributeValuePairListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceSynchronisationRelationshipType", namespace = "urn:gs1:gdsn:price_synchronisation_document:xsd:3", propOrder = {
    "priceSynchronisationRelationshipIdentification",
    "relationshipActionCode",
    "relationshipCurrencyCode",
    "relationshipEffectiveStartDateTime",
    "relationshipLastChangedDateTime",
    "relationshipTradeChannel",
    "targetMarketCountryCode",
    "priceSynchronisationRelationshipName",
    "relationshipEffectiveEndDateTime",
    "specialScenarioCode",
    "incotermInformation",
    "businessLocation",
    "informationProvider",
    "partyReceivingPrivateData",
    "extension",
    "avpList"
})
public class PriceSynchronisationRelationshipType {

    @XmlElement(required = true)
    protected EntityIdentificationType priceSynchronisationRelationshipIdentification;
    @XmlElement(required = true)
    protected SegmentActionCodeType relationshipActionCode;
    @XmlElement(required = true)
    protected CurrencyCodeType relationshipCurrencyCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar relationshipEffectiveStartDateTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar relationshipLastChangedDateTime;
    @XmlElement(required = true)
    protected TradeChannelCodeType relationshipTradeChannel;
    @XmlElement(required = true)
    protected CountryCodeType targetMarketCountryCode;
    protected String priceSynchronisationRelationshipName;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar relationshipEffectiveEndDateTime;
    protected List<PriceSynchronisationSpecialScenarioCodeType> specialScenarioCode;
    protected List<IncotermInformationType> incotermInformation;
    @XmlElement(required = true)
    protected PartyIdentificationType businessLocation;
    @XmlElement(required = true)
    protected PartyIdentificationType informationProvider;
    @XmlElement(required = true)
    protected PartyIdentificationType partyReceivingPrivateData;
    protected ExtensionType extension;
    protected GS1AttributeValuePairListType avpList;

    /**
     * Gets the value of the priceSynchronisationRelationshipIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link EntityIdentificationType }
     *     
     */
    public EntityIdentificationType getPriceSynchronisationRelationshipIdentification() {
        return priceSynchronisationRelationshipIdentification;
    }

    /**
     * Sets the value of the priceSynchronisationRelationshipIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityIdentificationType }
     *     
     */
    public void setPriceSynchronisationRelationshipIdentification(EntityIdentificationType value) {
        this.priceSynchronisationRelationshipIdentification = value;
    }

    /**
     * Gets the value of the relationshipActionCode property.
     * 
     * @return
     *     possible object is
     *     {@link SegmentActionCodeType }
     *     
     */
    public SegmentActionCodeType getRelationshipActionCode() {
        return relationshipActionCode;
    }

    /**
     * Sets the value of the relationshipActionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SegmentActionCodeType }
     *     
     */
    public void setRelationshipActionCode(SegmentActionCodeType value) {
        this.relationshipActionCode = value;
    }

    /**
     * Gets the value of the relationshipCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getRelationshipCurrencyCode() {
        return relationshipCurrencyCode;
    }

    /**
     * Sets the value of the relationshipCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setRelationshipCurrencyCode(CurrencyCodeType value) {
        this.relationshipCurrencyCode = value;
    }

    /**
     * Gets the value of the relationshipEffectiveStartDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRelationshipEffectiveStartDateTime() {
        return relationshipEffectiveStartDateTime;
    }

    /**
     * Sets the value of the relationshipEffectiveStartDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRelationshipEffectiveStartDateTime(XMLGregorianCalendar value) {
        this.relationshipEffectiveStartDateTime = value;
    }

    /**
     * Gets the value of the relationshipLastChangedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRelationshipLastChangedDateTime() {
        return relationshipLastChangedDateTime;
    }

    /**
     * Sets the value of the relationshipLastChangedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRelationshipLastChangedDateTime(XMLGregorianCalendar value) {
        this.relationshipLastChangedDateTime = value;
    }

    /**
     * Gets the value of the relationshipTradeChannel property.
     * 
     * @return
     *     possible object is
     *     {@link TradeChannelCodeType }
     *     
     */
    public TradeChannelCodeType getRelationshipTradeChannel() {
        return relationshipTradeChannel;
    }

    /**
     * Sets the value of the relationshipTradeChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeChannelCodeType }
     *     
     */
    public void setRelationshipTradeChannel(TradeChannelCodeType value) {
        this.relationshipTradeChannel = value;
    }

    /**
     * Gets the value of the targetMarketCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeType }
     *     
     */
    public CountryCodeType getTargetMarketCountryCode() {
        return targetMarketCountryCode;
    }

    /**
     * Sets the value of the targetMarketCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeType }
     *     
     */
    public void setTargetMarketCountryCode(CountryCodeType value) {
        this.targetMarketCountryCode = value;
    }

    /**
     * Gets the value of the priceSynchronisationRelationshipName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceSynchronisationRelationshipName() {
        return priceSynchronisationRelationshipName;
    }

    /**
     * Sets the value of the priceSynchronisationRelationshipName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceSynchronisationRelationshipName(String value) {
        this.priceSynchronisationRelationshipName = value;
    }

    /**
     * Gets the value of the relationshipEffectiveEndDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRelationshipEffectiveEndDateTime() {
        return relationshipEffectiveEndDateTime;
    }

    /**
     * Sets the value of the relationshipEffectiveEndDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRelationshipEffectiveEndDateTime(XMLGregorianCalendar value) {
        this.relationshipEffectiveEndDateTime = value;
    }

    /**
     * Gets the value of the specialScenarioCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialScenarioCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialScenarioCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriceSynchronisationSpecialScenarioCodeType }
     * 
     * 
     */
    public List<PriceSynchronisationSpecialScenarioCodeType> getSpecialScenarioCode() {
        if (specialScenarioCode == null) {
            specialScenarioCode = new ArrayList<PriceSynchronisationSpecialScenarioCodeType>();
        }
        return this.specialScenarioCode;
    }

    /**
     * Gets the value of the incotermInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incotermInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncotermInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncotermInformationType }
     * 
     * 
     */
    public List<IncotermInformationType> getIncotermInformation() {
        if (incotermInformation == null) {
            incotermInformation = new ArrayList<IncotermInformationType>();
        }
        return this.incotermInformation;
    }

    /**
     * Gets the value of the businessLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentificationType }
     *     
     */
    public PartyIdentificationType getBusinessLocation() {
        return businessLocation;
    }

    /**
     * Sets the value of the businessLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentificationType }
     *     
     */
    public void setBusinessLocation(PartyIdentificationType value) {
        this.businessLocation = value;
    }

    /**
     * Gets the value of the informationProvider property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentificationType }
     *     
     */
    public PartyIdentificationType getInformationProvider() {
        return informationProvider;
    }

    /**
     * Sets the value of the informationProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentificationType }
     *     
     */
    public void setInformationProvider(PartyIdentificationType value) {
        this.informationProvider = value;
    }

    /**
     * Gets the value of the partyReceivingPrivateData property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentificationType }
     *     
     */
    public PartyIdentificationType getPartyReceivingPrivateData() {
        return partyReceivingPrivateData;
    }

    /**
     * Sets the value of the partyReceivingPrivateData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentificationType }
     *     
     */
    public void setPartyReceivingPrivateData(PartyIdentificationType value) {
        this.partyReceivingPrivateData = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setExtension(ExtensionType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the avpList property.
     * 
     * @return
     *     possible object is
     *     {@link GS1AttributeValuePairListType }
     *     
     */
    public GS1AttributeValuePairListType getAvpList() {
        return avpList;
    }

    /**
     * Sets the value of the avpList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GS1AttributeValuePairListType }
     *     
     */
    public void setAvpList(GS1AttributeValuePairListType value) {
        this.avpList = value;
    }

}
