//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.18 at 01:24:23 AM AEDT 
//


package com.ascention.GS1.pricing.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferenceDocumentInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceDocumentInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="referenceDocumentIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="referenceDocumentDescription" type="{urn:gs1:shared:shared_common:xsd:3}Description70Type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceDocumentInformationType", namespace = "urn:gs1:gdsn:price_synchronisation_document:xsd:3", propOrder = {
    "referenceDocumentIdentifier",
    "referenceDocumentDescription"
})
public class ReferenceDocumentInformationType {

    @XmlElement(required = true)
    protected String referenceDocumentIdentifier;
    protected Description70Type referenceDocumentDescription;

    /**
     * Gets the value of the referenceDocumentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceDocumentIdentifier() {
        return referenceDocumentIdentifier;
    }

    /**
     * Sets the value of the referenceDocumentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceDocumentIdentifier(String value) {
        this.referenceDocumentIdentifier = value;
    }

    /**
     * Gets the value of the referenceDocumentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Description70Type }
     *     
     */
    public Description70Type getReferenceDocumentDescription() {
        return referenceDocumentDescription;
    }

    /**
     * Sets the value of the referenceDocumentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description70Type }
     *     
     */
    public void setReferenceDocumentDescription(Description70Type value) {
        this.referenceDocumentDescription = value;
    }

}
