//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.18 at 01:24:23 AM AEDT 
//


package com.ascention.GS1.pricing.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SegmentEffectiveStartDateInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SegmentEffectiveStartDateInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="effectiveStartDateContextCode" type="{urn:gs1:gdsn:price_synchronisation_document:xsd:3}EffectiveStartDateContextCodeType"/&gt;
 *         &lt;element name="effectiveStartDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SegmentEffectiveStartDateInformationType", namespace = "urn:gs1:gdsn:price_synchronisation_document:xsd:3", propOrder = {
    "effectiveStartDateContextCode",
    "effectiveStartDateTime"
})
public class SegmentEffectiveStartDateInformationType {

    @XmlElement(required = true)
    protected EffectiveStartDateContextCodeType effectiveStartDateContextCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar effectiveStartDateTime;

    /**
     * Gets the value of the effectiveStartDateContextCode property.
     * 
     * @return
     *     possible object is
     *     {@link EffectiveStartDateContextCodeType }
     *     
     */
    public EffectiveStartDateContextCodeType getEffectiveStartDateContextCode() {
        return effectiveStartDateContextCode;
    }

    /**
     * Sets the value of the effectiveStartDateContextCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EffectiveStartDateContextCodeType }
     *     
     */
    public void setEffectiveStartDateContextCode(EffectiveStartDateContextCodeType value) {
        this.effectiveStartDateContextCode = value;
    }

    /**
     * Gets the value of the effectiveStartDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveStartDateTime() {
        return effectiveStartDateTime;
    }

    /**
     * Sets the value of the effectiveStartDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveStartDateTime(XMLGregorianCalendar value) {
        this.effectiveStartDateTime = value;
    }

}
