//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.29 at 09:10:27 PM AEDT 
//


package com.ascention.GS1.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdditionalTradeItemClassificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalTradeItemClassificationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="additionalTradeItemClassificationSystemCode" type="{urn:gs1:gdsn:gdsn_common:xsd:3}AdditionalTradeItemClassificationCodeListCodeType" minOccurs="0"/&gt;
 *         &lt;element name="additionalTradeItemClassificationValue" type="{urn:gs1:gdsn:trade_item:xsd:3}AdditionalTradeItemClassificationValueType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalTradeItemClassificationType", namespace = "urn:gs1:gdsn:trade_item:xsd:3", propOrder = {
    "additionalTradeItemClassificationSystemCode",
    "additionalTradeItemClassificationValue"
})
public class AdditionalTradeItemClassificationType {

    protected AdditionalTradeItemClassificationCodeListCodeType additionalTradeItemClassificationSystemCode;
    protected List<AdditionalTradeItemClassificationValueType> additionalTradeItemClassificationValue;

    /**
     * Gets the value of the additionalTradeItemClassificationSystemCode property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalTradeItemClassificationCodeListCodeType }
     *     
     */
    public AdditionalTradeItemClassificationCodeListCodeType getAdditionalTradeItemClassificationSystemCode() {
        return additionalTradeItemClassificationSystemCode;
    }

    /**
     * Sets the value of the additionalTradeItemClassificationSystemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalTradeItemClassificationCodeListCodeType }
     *     
     */
    public void setAdditionalTradeItemClassificationSystemCode(AdditionalTradeItemClassificationCodeListCodeType value) {
        this.additionalTradeItemClassificationSystemCode = value;
    }

    /**
     * Gets the value of the additionalTradeItemClassificationValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalTradeItemClassificationValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalTradeItemClassificationValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalTradeItemClassificationValueType }
     * 
     * 
     */
    public List<AdditionalTradeItemClassificationValueType> getAdditionalTradeItemClassificationValue() {
        if (additionalTradeItemClassificationValue == null) {
            additionalTradeItemClassificationValue = new ArrayList<AdditionalTradeItemClassificationValueType>();
        }
        return this.additionalTradeItemClassificationValue;
    }

}
