//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.15 at 04:10:57 PM AEDT 
//


package com.ascention.GS1.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.sun.xml.txw2.annotation.XmlElement;


/**
 * <p>Java class for AlcoholInformationModuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlcoholInformationModuleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="alcoholInformation" type="{urn:gs1:gdsn:alcohol_information:xsd:3}AlcoholInformationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlcoholInformationModule", namespace = "urn:gs1:gdsn:alcohol_information:xsd:3", propOrder = {
    "alcoholInformation"
})
@XmlRootElement(name = "alcoholInformationModule",namespace = "urn:gs1:gdsn:alcohol_information:xsd:3")
public class AlcoholInformationModuleType {

    protected AlcoholInformationType alcoholInformation;

    /**
     * Gets the value of the alcoholInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AlcoholInformationType }
     *     
     */
    public AlcoholInformationType getAlcoholInformation() {
        return alcoholInformation;
    }

    /**
     * Sets the value of the alcoholInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlcoholInformationType }
     *     
     */
    public void setAlcoholInformation(AlcoholInformationType value) {
        this.alcoholInformation = value;
    }

}
