//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.29 at 08:20:58 PM AEDT 
//


package com.ascention.GS1.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CatalogueItemStateEnumerationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CatalogueItemStateEnumerationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CANCELED"/&gt;
 *     &lt;enumeration value="DISCONTINUED"/&gt;
 *     &lt;enumeration value="IN_PROGRESS"/&gt;
 *     &lt;enumeration value="REGISTERED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CatalogueItemStateEnumerationType", namespace = "urn:gs1:gdsn:catalogue_item_notification:xsd:3")
@XmlEnum
public enum CatalogueItemStateEnumerationType {

    CANCELED,
    DISCONTINUED,
    IN_PROGRESS,
    REGISTERED;

    public String value() {
        return name();
    }

    public static CatalogueItemStateEnumerationType fromValue(String v) {
        return valueOf(v);
    }

}
