//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.29 at 09:22:51 PM AEDT 
//


package com.ascention.GS1.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CertificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="certificationValue"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="200"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="certificateIssuanceDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="certificationAssessmentDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="certificationEffectiveEndDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="certificationEffectiveStartDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="certificationIdentification" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="35"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="referencedFileInformation" type="{urn:gs1:gdsn:gdsn_common:xsd:3}ReferencedFileInformationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="avpList" type="{urn:gs1:gdsn:gdsn_common:xsd:3}GS1_AttributeValuePairListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificationType", namespace = "urn:gs1:gdsn:gdsn_common:xsd:3", propOrder = {
    "certificationValue",
    "certificateIssuanceDateTime",
    "certificationAssessmentDateTime",
    "certificationEffectiveEndDateTime",
    "certificationEffectiveStartDateTime",
    "certificationIdentification",
    "referencedFileInformation",
    "avpList"
})
public class CertificationType {

    @XmlElement(required = true)
    protected String certificationValue;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar certificateIssuanceDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar certificationAssessmentDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar certificationEffectiveEndDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar certificationEffectiveStartDateTime;
    protected String certificationIdentification;
    protected List<ReferencedFileInformationType> referencedFileInformation;
    protected GS1AttributeValuePairListType avpList;

    /**
     * Gets the value of the certificationValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationValue() {
        return certificationValue;
    }

    /**
     * Sets the value of the certificationValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationValue(String value) {
        this.certificationValue = value;
    }

    /**
     * Gets the value of the certificateIssuanceDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertificateIssuanceDateTime() {
        return certificateIssuanceDateTime;
    }

    /**
     * Sets the value of the certificateIssuanceDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertificateIssuanceDateTime(XMLGregorianCalendar value) {
        this.certificateIssuanceDateTime = value;
    }

    /**
     * Gets the value of the certificationAssessmentDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertificationAssessmentDateTime() {
        return certificationAssessmentDateTime;
    }

    /**
     * Sets the value of the certificationAssessmentDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertificationAssessmentDateTime(XMLGregorianCalendar value) {
        this.certificationAssessmentDateTime = value;
    }

    /**
     * Gets the value of the certificationEffectiveEndDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertificationEffectiveEndDateTime() {
        return certificationEffectiveEndDateTime;
    }

    /**
     * Sets the value of the certificationEffectiveEndDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertificationEffectiveEndDateTime(XMLGregorianCalendar value) {
        this.certificationEffectiveEndDateTime = value;
    }

    /**
     * Gets the value of the certificationEffectiveStartDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertificationEffectiveStartDateTime() {
        return certificationEffectiveStartDateTime;
    }

    /**
     * Sets the value of the certificationEffectiveStartDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertificationEffectiveStartDateTime(XMLGregorianCalendar value) {
        this.certificationEffectiveStartDateTime = value;
    }

    /**
     * Gets the value of the certificationIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationIdentification() {
        return certificationIdentification;
    }

    /**
     * Sets the value of the certificationIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationIdentification(String value) {
        this.certificationIdentification = value;
    }

    /**
     * Gets the value of the referencedFileInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referencedFileInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferencedFileInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferencedFileInformationType }
     * 
     * 
     */
    public List<ReferencedFileInformationType> getReferencedFileInformation() {
        if (referencedFileInformation == null) {
            referencedFileInformation = new ArrayList<ReferencedFileInformationType>();
        }
        return this.referencedFileInformation;
    }

    /**
     * Gets the value of the avpList property.
     * 
     * @return
     *     possible object is
     *     {@link GS1AttributeValuePairListType }
     *     
     */
    public GS1AttributeValuePairListType getAvpList() {
        return avpList;
    }

    /**
     * Sets the value of the avpList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GS1AttributeValuePairListType }
     *     
     */
    public void setAvpList(GS1AttributeValuePairListType value) {
        this.avpList = value;
    }

}
