//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.29 at 08:35:39 PM AEDT 
//


package com.ascention.GS1.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DietTypeInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DietTypeInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dietTypeCode" type="{urn:gs1:gdsn:diet_information:xsd:3}DietTypeCodeType"/&gt;
 *         &lt;element name="dietTypeSubcode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="80"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dietCertification" type="{urn:gs1:gdsn:gdsn_common:xsd:3}CertificationInformationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DietTypeInformationType", namespace = "urn:gs1:gdsn:diet_information:xsd:3", propOrder = {
    "dietTypeCode",
    "dietTypeSubcode",
    "dietCertification"
})
public class DietTypeInformationType {

    @XmlElement(required = true)
    protected DietTypeCodeType dietTypeCode;
    protected String dietTypeSubcode;
    protected CertificationInformationType dietCertification;

    /**
     * Gets the value of the dietTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link DietTypeCodeType }
     *     
     */
    public DietTypeCodeType getDietTypeCode() {
        return dietTypeCode;
    }

    /**
     * Sets the value of the dietTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DietTypeCodeType }
     *     
     */
    public void setDietTypeCode(DietTypeCodeType value) {
        this.dietTypeCode = value;
    }

    /**
     * Gets the value of the dietTypeSubcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDietTypeSubcode() {
        return dietTypeSubcode;
    }

    /**
     * Sets the value of the dietTypeSubcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDietTypeSubcode(String value) {
        this.dietTypeSubcode = value;
    }

    /**
     * Gets the value of the dietCertification property.
     * 
     * @return
     *     possible object is
     *     {@link CertificationInformationType }
     *     
     */
    public CertificationInformationType getDietCertification() {
        return dietCertification;
    }

    /**
     * Sets the value of the dietCertification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificationInformationType }
     *     
     */
    public void setDietCertification(CertificationInformationType value) {
        this.dietCertification = value;
    }

}
