//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.29 at 08:59:18 PM AEDT 
//


package com.ascention.GS1.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NutritionalClaimDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NutritionalClaimDetailType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nutritionalClaimTypeCode" type="{urn:gs1:gdsn:nutritional_information:xsd:3}NutritionalClaimTypeCodeType" minOccurs="0"/&gt;
 *         &lt;element name="nutritionalClaimNutrientElementCode" type="{urn:gs1:gdsn:nutritional_information:xsd:3}NutritionalClaimNutrientElementCodeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NutritionalClaimDetailType", namespace = "urn:gs1:gdsn:nutritional_information:xsd:3", propOrder = {
    "nutritionalClaimTypeCode",
    "nutritionalClaimNutrientElementCode"
})
public class NutritionalClaimDetailType {

    protected NutritionalClaimTypeCodeType nutritionalClaimTypeCode;
    protected NutritionalClaimNutrientElementCodeType nutritionalClaimNutrientElementCode;

    /**
     * Gets the value of the nutritionalClaimTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link NutritionalClaimTypeCodeType }
     *     
     */
    public NutritionalClaimTypeCodeType getNutritionalClaimTypeCode() {
        return nutritionalClaimTypeCode;
    }

    /**
     * Sets the value of the nutritionalClaimTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NutritionalClaimTypeCodeType }
     *     
     */
    public void setNutritionalClaimTypeCode(NutritionalClaimTypeCodeType value) {
        this.nutritionalClaimTypeCode = value;
    }

    /**
     * Gets the value of the nutritionalClaimNutrientElementCode property.
     * 
     * @return
     *     possible object is
     *     {@link NutritionalClaimNutrientElementCodeType }
     *     
     */
    public NutritionalClaimNutrientElementCodeType getNutritionalClaimNutrientElementCode() {
        return nutritionalClaimNutrientElementCode;
    }

    /**
     * Sets the value of the nutritionalClaimNutrientElementCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NutritionalClaimNutrientElementCodeType }
     *     
     */
    public void setNutritionalClaimNutrientElementCode(NutritionalClaimNutrientElementCodeType value) {
        this.nutritionalClaimNutrientElementCode = value;
    }

}
