//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.29 at 08:59:18 PM AEDT 
//


package com.ascention.GS1.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NutritionalInformationModuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NutritionalInformationModuleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nutritionalClaim" type="{urn:gs1:shared:shared_common:xsd:3}Description5000Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="nutrientFormatTypeCodeReference" type="{urn:gs1:shared:shared_common:xsd:3}CodeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="descriptionOnANutrient" type="{urn:gs1:shared:shared_common:xsd:3}Description1000Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="isNutrientRelevantDataProvided" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="nutrientRelevantDataProvidedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="foodBeverageComposition" type="{urn:gs1:gdsn:nutritional_information:xsd:3}FoodBeverageCompositionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="nutritionalClaimDetail" type="{urn:gs1:gdsn:nutritional_information:xsd:3}NutritionalClaimDetailType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="nutrientHeader" type="{urn:gs1:gdsn:nutritional_information:xsd:3}NutrientHeaderType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="avpList" type="{urn:gs1:gdsn:gdsn_common:xsd:3}GS1_AttributeValuePairListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NutritionalInformationModuleType", namespace = "urn:gs1:gdsn:nutritional_information:xsd:3", propOrder = {
    "nutritionalClaim",
    "nutrientFormatTypeCodeReference",
    "descriptionOnANutrient",
    "isNutrientRelevantDataProvided",
    "nutrientRelevantDataProvidedDateTime",
    "foodBeverageComposition",
    "nutritionalClaimDetail",
    "nutrientHeader",
    "avpList"
})
@XmlRootElement(name = "nutritionalInformationModule",namespace = "urn:gs1:gdsn:nutritional_information:xsd:3")
public class NutritionalInformationModuleType {

    protected List<Description5000Type> nutritionalClaim;
    protected List<CodeType> nutrientFormatTypeCodeReference;
    protected List<Description1000Type> descriptionOnANutrient;
    protected Boolean isNutrientRelevantDataProvided;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar nutrientRelevantDataProvidedDateTime;
    protected List<FoodBeverageCompositionType> foodBeverageComposition;
    protected List<NutritionalClaimDetailType> nutritionalClaimDetail;
    protected List<NutrientHeaderType> nutrientHeader;
    protected GS1AttributeValuePairListType avpList;

    /**
     * Gets the value of the nutritionalClaim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nutritionalClaim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNutritionalClaim().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Description5000Type }
     * 
     * 
     */
    public List<Description5000Type> getNutritionalClaim() {
        if (nutritionalClaim == null) {
            nutritionalClaim = new ArrayList<Description5000Type>();
        }
        return this.nutritionalClaim;
    }

    /**
     * Gets the value of the nutrientFormatTypeCodeReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nutrientFormatTypeCodeReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNutrientFormatTypeCodeReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getNutrientFormatTypeCodeReference() {
        if (nutrientFormatTypeCodeReference == null) {
            nutrientFormatTypeCodeReference = new ArrayList<CodeType>();
        }
        return this.nutrientFormatTypeCodeReference;
    }

    /**
     * Gets the value of the descriptionOnANutrient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionOnANutrient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescriptionOnANutrient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Description1000Type }
     * 
     * 
     */
    public List<Description1000Type> getDescriptionOnANutrient() {
        if (descriptionOnANutrient == null) {
            descriptionOnANutrient = new ArrayList<Description1000Type>();
        }
        return this.descriptionOnANutrient;
    }

    /**
     * Gets the value of the isNutrientRelevantDataProvided property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsNutrientRelevantDataProvided() {
        return isNutrientRelevantDataProvided;
    }

    /**
     * Sets the value of the isNutrientRelevantDataProvided property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsNutrientRelevantDataProvided(Boolean value) {
        this.isNutrientRelevantDataProvided = value;
    }

    /**
     * Gets the value of the nutrientRelevantDataProvidedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNutrientRelevantDataProvidedDateTime() {
        return nutrientRelevantDataProvidedDateTime;
    }

    /**
     * Sets the value of the nutrientRelevantDataProvidedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNutrientRelevantDataProvidedDateTime(XMLGregorianCalendar value) {
        this.nutrientRelevantDataProvidedDateTime = value;
    }

    /**
     * Gets the value of the foodBeverageComposition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the foodBeverageComposition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFoodBeverageComposition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FoodBeverageCompositionType }
     * 
     * 
     */
    public List<FoodBeverageCompositionType> getFoodBeverageComposition() {
        if (foodBeverageComposition == null) {
            foodBeverageComposition = new ArrayList<FoodBeverageCompositionType>();
        }
        return this.foodBeverageComposition;
    }

    /**
     * Gets the value of the nutritionalClaimDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nutritionalClaimDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNutritionalClaimDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NutritionalClaimDetailType }
     * 
     * 
     */
    public List<NutritionalClaimDetailType> getNutritionalClaimDetail() {
        if (nutritionalClaimDetail == null) {
            nutritionalClaimDetail = new ArrayList<NutritionalClaimDetailType>();
        }
        return this.nutritionalClaimDetail;
    }

    /**
     * Gets the value of the nutrientHeader property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nutrientHeader property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNutrientHeader().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NutrientHeaderType }
     * 
     * 
     */
    public List<NutrientHeaderType> getNutrientHeader() {
        if (nutrientHeader == null) {
            nutrientHeader = new ArrayList<NutrientHeaderType>();
        }
        return this.nutrientHeader;
    }

    /**
     * Gets the value of the avpList property.
     * 
     * @return
     *     possible object is
     *     {@link GS1AttributeValuePairListType }
     *     
     */
    public GS1AttributeValuePairListType getAvpList() {
        return avpList;
    }

    /**
     * Sets the value of the avpList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GS1AttributeValuePairListType }
     *     
     */
    public void setAvpList(GS1AttributeValuePairListType value) {
        this.avpList = value;
    }

}
